export const CartData = [
  {
    id: 0,
    name: "Bell Pepper",
    image: "assests/images/product-1.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "180",
    disocuntedPrice: "40",
    category: "Vegetables",
    freshnesslevel: "90%",
    quantity: 2,
  },
  {
    id: 1,
    name: "Green Beans",
    image: "assests/images/product-3.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "200",
    disocuntedPrice: "40",
    category: "Vegetables",
    freshnesslevel: "50%",
    quantity: 1,
  },
  {
    id: 2,
    name: "Purple Cabbage",
    image: "assests/images/product-4.jpg",
    discount: "false",
    featured: "true",
    orignalPrice: "400",
    disocuntedPrice: "400",
    category: "Vegetables",
    freshnesslevel: "80%",
    quantity: 1,
  },
];
