export const Vegetables = [
  {
    id: 0,
    name: "Bell Pepper",
    image: "../../assests/images/product-1.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "$180",
    disocuntedPrice: "$40",
    category: "Vegetables",
    freshnesslevel: "90%",
  },
  {
    id: 1,
    name: "Green Beans",
    image: "../../assests/images/product-3.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "$200",
    disocuntedPrice: "$40",
    category: "Vegetables",
    freshnesslevel: "50%",
  },
  {
    id: 2,
    name: "Purple Cabbage",
    image: "../../assests/images/product-4.jpg",
    discount: "false",
    featured: "true",
    orignalPrice: "$400",
    disocuntedPrice: "$400",
    category: "Vegetables",
    freshnesslevel: "80%",
  },
  {
    id: 3,
    name: "Tomatoe",
    image: "../../assests/images/product-5.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "$100",
    disocuntedPrice: "$90",
    category: "Vegetables",
    freshnesslevel: "75%",
  },
  {
    id: 4,
    name: "Tomatoe",
    image: "../../assests/images/product-5.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "$100",
    disocuntedPrice: "$90",
    category: "Fruits",
    freshnesslevel: "75%",
  },
  {
    id: 5,
    name: "Tomatoe",
    image: "../../assests/images/product-5.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "$100",
    disocuntedPrice: "$90",
    category: "Drieds",
    freshnesslevel: "75%",
  },
  {
    id: 6,
    name: "Tomatoe",
    image: "../../assests/images/product-5.jpg",
    discount: "true",
    featured: "true",
    orignalPrice: "$100",
    disocuntedPrice: "$90",
    category: "Juices",
    freshnesslevel: "75%",
  },
];
